import type { Season, TeamGamesData } from '../types';
import { isPlayedSeason } from './seasonPlayed';
import teamGamesData from '../data/team-games.json';

/**
 * Per-season franchise game counts, for rebuilding the years a player spent
 * out of the league. Generated by `scripts/update-data.ts` into
 * `src/data/team-games.json`.
 *
 * `max` is the deepest run any franchise made that season — the same last
 * resort `resolveTeamGamesDenominator` falls back to when it cannot place a
 * player on a team.
 */
export type TeamGamesBySeason = Record<
  number | string,
  { max: number; byTeam: Record<string, number> }
>;

/** Every field a season row may carry that is not one of the six below. */
const RECONSTRUCTIBLE_KEYS = new Set([
  'year',
  'gamesPlayed',
  'teamGames',
  'snapShare',
  'cumulativeSnapShare',
  'retained',
]);

/**
 * Whether a season row holds nothing but the fact that a year went by.
 *
 * Once a player is out of the NFL, `update-data.ts` keeps emitting a row per
 * season through the newest played one — deliberately, because career-mode
 * scoring divides across every season since he entered the league and those
 * zeros are the penalty — settled under "Trailing out-of-league season rows"
 * in the repo's deferred-work notes. The rows are still *information
 * free*: given the player's franchise and the year, every field is implied.
 *
 * Only such a row may be elided from the stored JSON. Three near-misses are
 * excluded on purpose:
 *
 * - `retained: true` with no snaps is a real roster season — the player was
 *   held all year and never played. Ray Agnew's 2015 on Cleveland.
 * - `reserveWeeks`, `injuryReportWeeks` and friends mark a season spent injured
 *   rather than absent. Alex Lewis' 2021 is zero games of genuine NFL season.
 * - `teamGames === 0` is the offseason roster row, which says where a player
 *   stands ahead of a season nobody has played yet. See `./seasonPlayed`.
 */
export function isReconstructibleSeason(season: Season): boolean {
  if (!isPlayedSeason(season)) return false;
  if (season.retained) return false;
  if (season.gamesPlayed !== 0) return false;
  if (season.snapShare !== 0) return false;
  if ((season.cumulativeSnapShare ?? 0) !== 0) return false;
  return Object.keys(season).every((k) => RECONSTRUCTIBLE_KEYS.has(k));
}

/**
 * Index of the trailing offseason row, or the length when there is none.
 *
 * `buildCareerSeasons` appends at most one such row and always last, so
 * everything before this point is football that was played.
 */
function playedCount(seasons: Season[]): number {
  return seasons.length > 0 && !isPlayedSeason(seasons[seasons.length - 1])
    ? seasons.length - 1
    : seasons.length;
}

/**
 * Drops the run of out-of-league seasons a career ends on, keeping any
 * offseason row after it.
 *
 * Only a *suffix* is trimmed, never an interior year: a player who came back
 * after a season away keeps the gap year, because
 * {@link hydrateReconstructibleSeasons} refills from the end and would leave a
 * hole otherwise.
 *
 * Nothing is lost. The rows come back at parse time, and no score moves —
 * `getPlayerDraftScore` sees the same seasons it always did.
 */
export function trimReconstructibleSeasons(seasons: Season[]): Season[] {
  const offseason = seasons.slice(playedCount(seasons));
  let end = playedCount(seasons);
  while (end > 0 && isReconstructibleSeason(seasons[end - 1])) end--;
  return [...seasons.slice(0, end), ...offseason];
}

export interface HydrateOptions {
  /** The franchise that acquired the player, for the game-count lookup. */
  teamId: string;
  /**
   * The player's class year — his draft, or his debut for a free agent. Used
   * only when nothing at all remains, i.e. he never played a down.
   */
  fromSeason: number;
  /** Newest played season in the dataset, the year the rows run out to. */
  throughSeason: number;
  teamGames: TeamGamesBySeason;
}

/**
 * Puts back what {@link trimReconstructibleSeasons} elided, so everything
 * downstream sees the career exactly as the pipeline built it.
 *
 * Called at the single parse point for each file — `stampDraftYear` and
 * `stampFreeAgentYear` — before any scoring, caching or rendering. `src/lib`
 * and `src/components` therefore need no knowledge of this at all.
 *
 * A season the lookup has no game count for is skipped rather than guessed. A
 * fabricated `teamGames` would surface as a quietly wrong availability share
 * ("0 of 17 games" is rendered in `ScoreBreakdown`); a missing row surfaces as
 * a career that visibly stops short, which is the failure you can see.
 */
export function hydrateReconstructibleSeasons(
  seasons: Season[],
  options: HydrateOptions,
): Season[] {
  const { teamId, fromSeason, throughSeason, teamGames } = options;
  const played = seasons.slice(0, playedCount(seasons));
  const offseason = seasons.slice(playedCount(seasons));

  const resumeFrom =
    played.length > 0 ? played[played.length - 1].year + 1 : fromSeason;

  const refilled: Season[] = [];
  for (let year = resumeFrom; year <= throughSeason; year++) {
    const counts = teamGames[year];
    if (!counts) continue;
    const games = counts.byTeam[teamId] ?? counts.max;
    if (games <= 0) continue;
    refilled.push({
      year,
      gamesPlayed: 0,
      teamGames: games,
      snapShare: 0,
      cumulativeSnapShare: 0,
      retained: false,
    });
  }

  return [...played, ...refilled, ...offseason];
}

/** The shipped game-count table, bundled rather than fetched: 8 KB. */
const SHIPPED_TEAM_GAMES = (teamGamesData as TeamGamesData).gamesBySeason;

/**
 * One acquisition's seasons, restored against the shipped game-count table.
 *
 * This is the form the parse points use. `seasonsThrough` is the class file's
 * own `seasonsThrough` — the season the pipeline wrote rows out to before
 * eliding the ones it could rebuild. **When it is absent, nothing is added.**
 *
 * That is what keeps the elision explicit rather than inferred. A class built
 * by hand in a test, or a file from a deploy that predates the trim, states no
 * horizon and is therefore passed through untouched; only a file that says it
 * was trimmed gets rows put back. Deriving the horizon from `LATEST_SEASON`
 * instead would quietly extend every short career it was ever handed.
 *
 * `classYear` is the pick's draft year or the free agent's debut season, taken
 * from the enclosing class — the same trusted source `stampDraftYear` stamps
 * `draftYear` from, never `seasons[0].year`.
 */
export function hydrateAcquisitionSeasons(
  seasons: Season[],
  teamId: string,
  classYear: number,
  seasonsThrough: number | undefined,
): Season[] {
  if (seasonsThrough == null) return seasons;
  return hydrateReconstructibleSeasons(seasons, {
    teamId,
    fromSeason: classYear,
    throughSeason: seasonsThrough,
    teamGames: SHIPPED_TEAM_GAMES,
  });
}
