#!/usr/bin/env npx tsx
/**
 * Fetch nflverse game results and write public/data/team-success.json:
 * real per-team, per-season regular-season records, playoff appearances and
 * Super Bowl results. Stored by season so the app can aggregate to whatever
 * year range the user selects.
 *
 * Source: nflverse/nfldata games.csv (Lee Sharpe). Committed to the repo like
 * the draft data — regenerated by `npm run update-data`, not at build time.
 *
 * Run: npx tsx scripts/generate-team-success.ts
 */
import * as fs from 'fs';
import * as path from 'path';
import { parse } from 'csv-parse/sync';
import {
  buildSeasonRecords,
  type GamesCsvRow,
  type TeamSuccessData,
} from '../src/lib/teamSuccess';

const GAMES_URL =
  'https://github.com/nflverse/nfldata/raw/master/data/games.csv';
// Every season with played results the app's draft data can pair with. 2026 is
// scheduled-only, so it contributes no records until games are played.
const FROM = 2018;
const TO = 2026;

async function main() {
  console.log('Fetching nflverse games.csv...');
  const res = await fetch(GAMES_URL);
  if (!res.ok) throw new Error(`HTTP ${res.status}: ${GAMES_URL}`);
  const rows = parse(await res.text(), {
    columns: true,
    skip_empty_lines: true,
  }) as GamesCsvRow[];

  const teams = buildSeasonRecords(rows, FROM, TO);
  const output: TeamSuccessData = { from: FROM, to: TO, teams };

  const outDir = path.join(process.cwd(), 'public', 'data');
  fs.mkdirSync(outDir, { recursive: true });
  const outPath = path.join(outDir, 'team-success.json');
  fs.writeFileSync(outPath, JSON.stringify(output));
  const seasonCount = teams.reduce((n, t) => n + t.seasons.length, 0);
  console.log(
    `Wrote ${seasonCount} team-seasons for ${teams.length} teams (${FROM}–${TO}) to ${outPath}`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
